CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS postdb;
CREATE DATABASE IF NOT EXISTS commentdb;
CREATE DATABASE IF NOT EXISTS likedb;
CREATE DATABASE IF NOT EXISTS followdb;
CREATE DATABASE IF NOT EXISTS notificationdb;
CREATE DATABASE IF NOT EXISTS mediadb;
CREATE DATABASE IF NOT EXISTS searchdb;
